# espanso configuration file

# This is the default configuration file, change it as you like it
# You can refer to the official documentation:
# https://espanso.org/docs/

use_system_agent: false

# Matches are the substitution rules, when you type the "trigger" string
# it gets replaced by the "replace" string.
matches:
  # Eñe
  - trigger: "'n"
    replace: "ñ"

  - trigger: "'N"
    replace: "Ñ"

  # Acentos
  - trigger: "'a"
    replace: "á"

  - trigger: "'A"
    replace: "Á"

  - trigger: "'e"
    replace: "é"

  - trigger: "'E"
    replace: "É"

  - trigger: "'i"
    replace: "í"

  - trigger: "'I"
    replace: "Í"

  - trigger: "'o"
    replace: "ó"

  - trigger: "'O"
    replace: "Ó"

  - trigger: "'u"
    replace: "ú"

  - trigger: "'U"
    replace: "Ú"

  # Diéresis
  - trigger: "\"u"
    replace: "ü"

  - trigger: "\"U"
    replace: "Ü"

  # Otros signos
  - trigger: "'!"
    replace: "¡"

  - trigger: "'?"
    replace: "¿"

  - trigger: "MJA"
    replace: "Mario Emilio Jiménez Vizcaíno A01173359"
